import { AlbumConfiguration } from "~/types/album-configuration.type";

export const INITIAL_VALUES: AlbumConfiguration = {
  albumPath: "",
  chapterEnd: 1_000_000_000,
  chapterIndexLen: 4,
  chapterIndices: [],
  chapterLinkQuery: "",
  chapterStart: 0,
  downloadDir: "",
  getChapterIndex: () => "",
  getChapterName: () => "",
  getLinkFromTag: () => "",
  getSourceFromTag: () => "",
  imageIndexLen: 3,
  imageSourceQuery: "",
  isReverseOrder: true,
  loggingLevel: "all",
  maxChapterWorkers: 5,
  maxImageProcesses: 5,
  maxRetryAttemptsPerChapter: 3,
  maxRetryAttemptsPerImage: 3,
  shouldCheckHealth: true,
  shouldDetectUpdates: true,
  shouldDownloadUpdates: true,
  shouldRetryChapters: true,
  shouldRetryImages: true,
  shouldScrape: true,
  slug: "",
  startingHealthCheckChapterIndex: 1,
  startingHealthCheckImageIndex: 0,
  startingUrl: "",
  useSlugOnDownloadPath: false,
};
